name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake make pkg-config libboost-all-dev \
            libhts-dev libbdsg-dev libhandlegraph-dev libsdsl-dev

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      
    - name: Build project
      run: cmake --build build -- -j$(nproc)

    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure
