name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository with submodules
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libomp-dev doxygen libjansson-dev
        mkdir -p build
        cd build
        cmake .. -DRUN_DOXYGEN=ON -DPYTHON_EXECUTABLE="$(which python3)"
        echo "Build with $(nproc) threads"
        make -j$(nproc) VERBOSE=1

    # Step 5: Install other dependencies
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "requirements.txt not found"; fi

    # Step 6: Run tests
    - name: Run tests
      run: python3 -m pytest
