name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install requirements dependencies
      run: pip install -r requirements.txt
      
    - name: Install libbdsg
      run: |
        sudo apt-get install -y libomp-dev doxygen libjansson-dev
        git clone --recursive https://github.com/vgteam/libbdsg.git && cd libbdsg && pip install .

    - name: Run pytest tests
      run: python3 -m pytest
