name: Python CI

# Trigger the workflow on pushes and pull requests to the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    # Run tests on the latest Ubuntu
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies and libbdsg
      run: |
        python -m pip install --upgrade pip
        # Install libbdsg by cloning and installing from its directory
        git clone --recursive https://github.com/vgteam/libbdsg.git
        cd libbdsg
        pip install .
        cd ..
        # Install other dependencies from requirements.txt
        pip install -r requirements.txt

    # Step 4: Run tests
    - name: Run tests
      run: pytest
